use_frameworks!

platform :ios, '10.0'

target 'NetworkingLibrary_Example' do
  pod 'NetworkingLibrary', :path => '../'

  target 'NetworkingLibrary_Tests' do
    inherit! :search_paths

    
  end
end
